### ISSUE TITLE
Pronoun DB Plugin for Discord App Not Working

### ISSUE THREAD

**Issue by minecaftakiva** [cyyynthia/pronoundb.org#71]
On startup, Discord says, 
`TypeError: Cannot read property 'SingleSelect' of undefined
    at eval (betterdiscord://plugins/PronounDB.plugin.js:5002:126)
    at eval (betterdiscord://plugins/PronounDB.plugin.js:5217:5)
    at buildPlugin (betterdiscord://plugins/PronounDB.plugin.js:5219:4)
    at eval (betterdiscord://plugins/PronounDB.plugin.js:5224:2)
    at Object.requireAddon (<anonymous>:4:39280)
    at Object.loadAddon (<anonymous>:4:9251)
    at Object.loadAddon (<anonymous>:4:36952)
    at Object.loadAllAddons (<anonymous>:4:11725)
    at Object.initialize (<anonymous>:4:6147)
    at Object.initialize (<anonymous>:4:36147)
    at Object.startup (<anonymous>:4:396593)`
    and you can't turn on the plugin in settings. 

Thanks!

**Comment by cyyynthia** [comment]
I am not the author nor the maintainer of the BetterDiscord plugin. You'll need to report this to them if it hasn't been reported already, not me!
